services:
  gnome-docker:
    container_name: gnome-docker
    hostname: gnome-docker
    build: ./host/gnome-docker

    environment:
      VNC_OPTION: -SecurityTypes=None -rfbunixpath /host/vncsocket -rfbport 5900
      BEFORE_GNOME: "/extension/install.sh dev-guest"
      ROOTMODE: false
      XVFB_GPU: false
      XVFB_SCREEN_WIDTH: 1080
      RDP_OPTION: "-auth /monitors:0"

    # Remote
    ports:
      # for rdp
      - 3389:3389
      # for vnc
      - 5900:5900

    # For systemd
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cgroup: host

    # Mounts
    volumes:
      # Systemd requirements
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /sys/fs/cgroup/system.slice:/sys/fs/cgroup/system.slice:rw

      # Host dir
      - ./host:/host:rw
      - ./:/extension
      - ./host/home:/home/gnome
